config/routes.rb
Rails.application.routes.draw do

  namespace 'api' do
      namespace 'v1' do
        resources :students, only: :index
        get 'students/get_student'
      end
  end

  resources :student_performances
  resources :student_schools
  resources :schools
  resources :students
  resources :users
  
  #resources :reports, only: [:show]
  get 'reports/index'
  get 'reports/performance_pdf' , to: 'reports#performance_pdf'
  get 'reports/pdf' , to: 'reports#show'
  get 'reports/performance_graph' , to: 'reports#performance_graph'
  

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

 
  root 'sessions#new'



  


  get '/search' => 'welcome#index', :as => 'search_page'
  get 'students/register' => 'students#new', :as => 'register'
  get '/students/student_register', to: 'students#new'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student_performance.rb
class StudentPerformance < ApplicationRecord
    belongs_to :student
    belongs_to :school
end

app/controllers/student_performances_controller.rb
class StudentPerformancesController < ApplicationController

     # the first code in action show, edit, update and destroy are the same, we hate the duplicated code, use before_filter to avoid.
    # duplicate code is @student_performance=StudentPerformance.find(params[:id])
    # Refactor
    before_action :find_student_formance, only: [:show, :edit, :update, :destroy]
    
        # this action method for diplay list of StudentPerformance
        # # GET /student_performances
        def index
            
            @student_filter=StudentPerformance.new #this variable for using with form_for for searching       
            
            #for fix error first time loading
             if params[:student_performance].present?
                 @school_year = params[:student_performance][:school_year]
                 @school_id = params[:student_performance][:school_id]
                 @grade = params[:student_performance][:grade]
                 @student_name =params[:student_performance][:student_name]
                 @caption_button_student="ViewPerformance" # for hight on menu when click on search
                 @student_performance=StudentPerformance.joins(:student).order(:id)
             else
                 @student_performance=StudentPerformance.order(:id) # first time load
             end
            
             @student_performance=@student_performance.where(school_year: @school_year) if @school_year.present?
             @student_performance=@student_performance.where(school_id: @school_id) if @school_id.present?
             @student_performance=@student_performance.where(grade: @grade) if @grade.present?
             @student_performance=@student_performance.where("student_name like ?", "%#{@student_name}%") if @student_name.present?
        



        end
        
        #this action method for getting information detail for a StudentPerformance
        # GET /student_performances/1
        def show
             # Look up the existing model record based
             # on an ID from the request path.
             #@student_performance=StudentPerformance.find(params[:id])
        end
        #this action method for new StudentPerformance when user click button new StudentPerformance
        # # GET /student_performances/new
        def new
            @student_performance=StudentPerformance.new
            @caption_button_student_performance="Add"
        end
    
        #this action method for save StudentPerformance information into database when user click on button add
        # POST /student_performances
        def create 
            @student_performance = StudentPerformance.new(student_params)
            if @student_performance.save
              redirect_to edit_student_performance_path(@student_performance)
            else
              render :new
            end   
        end    
        #this action method for getting a StudentPerformance's information to edit when user click on button edit
        #GET /student_performances/1/edit
        def edit
            #@student_performance = StudentPerformance.find(params[:id])
            @caption_button_student_performance="Update" #this variable use to cheng the lable of button in StudentPerformance form partial to Update
    
        end
    
        #this action method for update a StudentPerformance's information into database when user click button update
        ## PATCH/PUT /student_performances/1
        def update
            #@student_performance = StudentPerformance.find(params[:id])
            # the existing model record. 
            if @student_performance.update(student_params)
    
                # Redirect the browser to edit of StudentPerformance
                redirect_to edit_student_performance_path
              else
                # Redirect the browser to edit of StudentPerformance
                render :edit
              end
          end
    
        #this action method for deleting a StudentPerformance'sinformation from database when user click on button delete
        def destroy
            #@student_performance= StudentPerformance.find(params[:id])
            @student_performance.destroy
            redirect_to stuent_performances_path
          end
    
        #this method is used for getting information from parameter when user click on button register or update
        #is used to filter the trusted parameters with a white list
        # Never trust parameters from the scary internet, only allow the white list through
        private
        def student_params
          params.require(:student_performance).permit(:school_year, :school_id, :student_id, :grade,:math_s1,:khmer_s1,:social_s1,:math_s2,:khmer_s2,:social_s2)
        end
    
        # Use callbacks to share common setup or constraints between actions.
        def find_student_formance
            # Look up the existing model record based
            # on an ID from the request path.
            @student_performance = StudentPerformance.find(params[:id])
          end

end

app/helpers/student_performances_helper.rb
module StudentPerformancesHelper
end

app/views/student_performances/_form.html.erb
<%
#[['Text', Value], ['Text', Value]]
school_year=[]                        
(2017..2019).each do |i|
    school_year.push([i.to_s+'-'+(i+1).to_s,i.to_s+'-'+(i+1).to_s])
end

grade=[]
(1..12).each do |i|
    grade.push(i.to_s)
end

%>

<%=form_for @student_performance do |f| %>
    
    <div class="card">
    <div class="card-body">
        <h4 class="card-title" style="color:brown;">Student Performance</h4>
        <hr class="m-t-0 m-b-40"> 
    
        <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label text-left col-md-4">School Year</label>
                        <div class="col-md-8">
                         
                        
                        <%= f.select :school_year, options_for_select(school_year,:selected => @student_performance.school_year), {include_blank: '-- Select One --'}, {class: 'form-control',:required => true}%>
    
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label text-left col-md-4">School Name</label>
                        <div class="col-md-8">
                          
                            <%= f.collection_select :school_id, School.order(:school_name),:id ,:school_name, { include_blank: '-- Select One --' }, { class: "form-control",:required => true } %>

                         </div>
                    </div>
                </div>
        </div>
    
        <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label text-left col-md-4">Grade</label>
                        <div class="col-md-8">

                        <%= f.select :grade, options_for_select(grade,:selected => @student_performance.grade), {include_blank: '-- Select One --'}, {class: 'form-control',:required => true}%>
                        

                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label text-left col-md-4">Student Name</label>
                        <div class="col-md-8">
                          
                        
                        <%= f.collection_select :student_id, Student.reorder(student_name: :asc),:id ,:student_name, { include_blank: '-- Select One --' }, { class: "form-control",:required => true } %>
                        
                        </div>
                    </div>
                </div>
        </div>

       
        <h5 class="box-title" style="color:brown;">Score Semester 1</h5>
        <hr class="m-t-0 m-b-40">

        <div class="row">
                    <div class="col-md-4">
                        <div class="form-group row">
                            <label class="control-label text-left col-md-4">Math</label>
                            <div class="col-md-8">
                                
                                <%=f.text_field :math_s1 , {class: 'form-control',required: true}%>

                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group row">
                            <label class="control-label text-left col-md-4">Khmer</label>
                            <div class="col-md-8">
                            <%=f.text_field :khmer_s1 , {class: 'form-control'}%>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4">
                    <div class="form-group row">
                        <label class="control-label text-left col-md-4">Social</label>
                        <div class="col-md-8">
                            
                            <%=f.text_field :social_s1 , {class: 'form-control',required: true}%>

                        </div>
                    </div>
                </div>

                    
            </div>  


        
        <h5 class="box-title" style="color:brown;">Score Semester 2</h5>
        <hr class="m-t-0 m-b-40">
        
        <div class="row">
                <div class="col-md-4">
                    <div class="form-group row">
                        <label class="control-label text-left col-md-4">Math</label>
                        <div class="col-md-8">
                            
                            <%=f.text_field :math_s2 , {class: 'form-control',required: true}%>

                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group row">
                        <label class="control-label text-left col-md-4">Khmer</label>
                        <div class="col-md-8">
                        <%=f.text_field :khmer_s2 , {class: 'form-control'}%>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                <div class="form-group row">
                    <label class="control-label text-left col-md-4">Social</label>
                    <div class="col-md-8">
                        
                        <%=f.text_field :social_s2 , {class: 'form-control',required: true}%>

                    </div>
                </div>
            </div>

                
        </div>  

        <!-- end form -->


    
        <div class="container text-center">              
                <div class="row button-group">    
                
                    <div class="col-lg-2 col-md-3 col-sm-4">
                       
                       <%= button_tag( :class => "btn btn-block btn-outline-success btn-rounded") do %>
                            <i class="fa fa-file-o"></i> <%=@caption_button_student_performance%>
                        <% end %>
                    </div>

                    <% if @caption_button_student_performance=='Update' %>
                        <div class="col-lg-2 col-md-3 col-sm-4">
                        
                            <%= button_tag(:type => 'button', :class => "btn btn-block btn-outline-success btn-rounded", :onclick => "javascript:location.href='#{new_student_performance_path()}'"    ) do %>
                                <i class="fa fa-file-o"> &nbsp;</i> New Student
                            <% end %>


                        </div>
                    <%end%>


                    <div class="col-lg-2 col-md-3 col-sm-4">   
                                          
                            <%= button_tag(:type => 'button', :class => "btn btn-block btn-outline-success btn-rounded", :onclick => "javascript:location.href='#{student_performances_path()}'"    ) do %>
                                <i class="fa fa-search-plus"></i> Go Find
                            <% end %>
                     </div>
        
    
                </div>
                
    
        </div>
    
        
     </div><!-- end card body-->
    </div> <!-- end card -->
    
    
    <%end%>

app/views/student_performances/edit.html.erb
<%= render 'form' %>

app/views/student_performances/index.html.erb
<%
#[['Text', Value], ['Text', Value]]
school_year=[]                        
(2017..2019).each do |i|
    school_year.push([i.to_s+'-'+(i+1).to_s,i.to_s+'-'+(i+1).to_s])
end

grade=[]
(1..12).each do |i|
    grade.push(i.to_s)
end

%>

<%= form_for(@student_filter, :url=> student_performances_path, :html => { :method => 'GET' }) do |f| %> 
        
<div class="card">
    <div class="card-body">
        <h4 class="card-title" style="color:brown;">Student Performance Information</h4>
        <hr class="m-t-0 m-b-40"> 

        <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label text-left col-md-4">School Year</label>
                        <div class="col-md-8">
                        <%= f.select :school_year, options_for_select(school_year,:selected => @school_year), {include_blank: '-- Select One --'}, {class: 'form-control'}%>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label text-left col-md-4">School Name</label>
                        <div class="col-md-8">
                        <%= f.collection_select :school_id, School.order(:school_name),:id ,:school_name, { include_blank: '-- Select One --' }, { class: "form-control" } %>
                        </div>
                    </div>
                </div>
        </div>

        <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label text-left col-md-4">Grade</label>
                        <div class="col-md-8">
                        <%= f.select :grade, options_for_select(grade,:selected =>@grade), {include_blank: '-- Select One --'}, {class: 'form-control'}%>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label text-left col-md-4">Student Name</label>
                        <div class="col-md-8">
                        <%=f.text_field :student_name , {class: 'form-control',value:@student_name} %>
                        </div>
                    </div>
                </div>
        </div>






        <hr class="m-t-0 m-b-40">

        <div class="container text-center">              
                <div class="row button-group">              
                        <div class="col-lg-2 col-md-3 col-sm-4">    
                            


                            <%= button_tag(:type => 'submit', :class => "btn btn-block btn-outline-success btn-rounded" ) do %>
                                <i class="fa fa-search-plus">&nbsp;</i>Find
                            <% end %>

                        </div>
        
                        <div class="col-lg-2 col-md-3 col-sm-4">
                            
                                <%= button_tag(:type => 'button', :class => "btn btn-block btn-outline-success btn-rounded", :onclick => "javascript:location.href='#{new_student_performance_path()}'"    ) do %>
                                    <i class="fa fa-file-o"> &nbsp;</i> New Student
                                <% end %>


                        </div>
                </div>
                

        </div>

        
    </div><!-- end card body-->
</div> <!-- end card -->

<% end %>



<div class="card">
<div class="card-body"> 
  <div class="row">
          <div class="col-12">
              
                  <div class="table-responsive m-t-40">
                          <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                              <thead>
                                  <tr>
                                      <th>No. </th>
                                      <th>School Year</th>
                                      <th>School Name</th>
                                      <th>Grade</th>
                                      <th>Student Name</th>
                                      <th>Score S1</th>
                                      <th>Avg. S1</th>
                                      <th>Score S2</th>   
                                      <th>Avg. S2</th>                                   
                                      <th>Action</th>
                                  </tr>
                              </thead>

                              <tbody>
                              
                                <% i=0 %>
                                <%@student_performance.each do |student_performance| %>
                                    <%i=i+1%>
                                    <%
                                    total_scoreS1=student_performance.math_s1+student_performance.khmer_s1+student_performance.social_s1
                                    avg_scoreS1=total_scoreS1/3

                                    total_scoreS2=student_performance.math_s2+student_performance.khmer_s2+student_performance.social_s2
                                    avg_scoreS2=total_scoreS2/3

                                    %>
                                    <tr>
                                    <td><%=i%></td>
                                    <td><%=student_performance.school_year%></td>
                                    <td><%=student_performance.school.school_name%></td>
                                    <td align="center"><%=student_performance.grade%></td> 
                                    <td><%=student_performance.student.student_name%></td>
                                    <td><%=total_scoreS1%></td>
                                    <td><%=avg_scoreS1%></td>
                                    <td><%=total_scoreS2%></td>
                                    <td><%=avg_scoreS2%></td>
                                    <td>
                                    <!-- Example single danger button -->
                                    <div class="btn-group">
                                            <button type="button" class="btn btn-sm btn-rounded btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="ti-settings"></i>
                                            </button>
                                            <div class="dropdown-menu">
                                               
                                                <%= link_to 'Delete', student_path(student_performance), class:'dropdown-item' %>
                                                <%= link_to 'Edit', edit_student_performance_path(student_performance), class:'dropdown-item' %>
                                                
       
                                               
                                            </div>
                                        </div>

                                    </td>
                                </tr>   

                                <%end%>   

                               </tbody>
                          </table>
                      </div>
          </div>
  </div>
</div>
</div>

app/views/student_performances/new.html.erb
<%= render 'form' %>