config/routes.rb
Rails.application.routes.draw do

  namespace 'api' do
      namespace 'v1' do
        resources :students, only: :index
        get 'students/get_student'
      end
  end

  resources :student_performances
  resources :student_schools
  resources :schools
  resources :students
  resources :users
  
  #resources :reports, only: [:show]
  get 'reports/index'
  get 'reports/performance_pdf' , to: 'reports#performance_pdf'
  get 'reports/pdf' , to: 'reports#show'
  get 'reports/performance_graph' , to: 'reports#performance_graph'
  

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

 
  root 'sessions#new'



  


  get '/search' => 'welcome#index', :as => 'search_page'
  get 'students/register' => 'students#new', :as => 'register'
  get '/students/student_register', to: 'students#new'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_header.html.erb
<header class="topbar">
<nav class="navbar top-navbar navbar-expand-md navbar-light">
    <!-- ============================================================== -->
    <!-- Logo -->
    <!-- ============================================================== -->
    <div class="navbar-header">
        <a class="navbar-brand" href="index.html">
            <!-- Logo icon --><b>
                <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                <!-- Dark Logo icon -->
                <img src="/assets/logo-icon.png" alt="homepage" class="dark-logo" />
                <!-- Light Logo icon -->
                <img src="/assets/logo-light-icon.png" alt="homepage" class="light-logo" />
            </b>
            <!--End Logo icon -->
            <!-- Logo text --><span>
            <!-- dark Logo text -->
            <!--<img src="/assets/logo-text.png" alt="homepage" class="dark-logo" />-->
            <!-- Light Logo text -->    
            <!--<img src="/assets/logo-light-text.png" class="light-logo" alt="homepage" />--></span> </a>
    </div>
    <!-- ============================================================== -->
    <!-- End Logo -->
    <!-- ============================================================== -->
    <div class="navbar-collapse">
        <!-- ============================================================== -->
        <!-- toggle and nav items -->
        <!-- ============================================================== -->
        <ul class="navbar-nav mr-auto mt-md-0">
            <!-- This is  -->
            <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="mdi mdi-menu"></i></a> </li>
            <li class="nav-item m-l-10"> <a class="nav-link sidebartoggler hidden-sm-down text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
            <!-- ============================================================== -->

        </ul>
        <!-- ============================================================== -->
        <!-- User profile and search -->
        <!-- ============================================================== -->
        <ul class="navbar-nav my-lg-0">
            <!-- ============================================================== -->
            <!-- Search -->
            <!-- ============================================================== -->
            <!--
            <li class="nav-item hidden-sm-down search-box"> <a class="nav-link hidden-sm-down text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="ti-search"></i></a>
                <form class="app-search">
                    <input type="text" class="form-control" placeholder="Search & enter"> <a class="srh-btn"><i class="ti-close"></i></a> </form>
            </li> -->
            
            <!-- ============================================================== -->
            <!-- Language -->
            <!-- ============================================================== -->
           
           <!--
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="flag-icon flag-icon-us"></i></a>
                <div class="dropdown-menu dropdown-menu-right scale-up"> <a class="dropdown-item" href="#"><i class="flag-icon flag-icon-in"></i> India</a> <a class="dropdown-item" href="#"><i class="flag-icon flag-icon-fr"></i> French</a> <a class="dropdown-item" href="#"><i class="flag-icon flag-icon-cn"></i> China</a> <a class="dropdown-item" href="#"><i class="flag-icon flag-icon-de"></i> Dutch</a> </div>
            </li>

            -->

            <!-- ============================================================== -->
            <!-- Profile -->
            <!-- ============================================================== -->
            <!--
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="/assets/users/1.jpg" alt="user" class="profile-pic" /></a>
                <div class="dropdown-menu dropdown-menu-right scale-up">
                    <ul class="dropdown-user">
                        <li>
                            <div class="dw-user-box">
                                <div class="u-img"><img src="/assets/users/1.jpg" alt="user"></div>
                                <div class="u-text">
                                    <h4>Steave Jobs</h4>
                                    <p class="text-muted">varun@gmail.com</p><a href="pages-profile.html" class="btn btn-rounded btn-danger btn-sm">View Profile</a></div>
                            </div>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#"><i class="ti-user"></i> My Profile</a></li>
                        <li><a href="#"><i class="ti-wallet"></i> My Balance</a></li>
                        <li><a href="#"><i class="ti-email"></i> Inbox</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#"><i class="ti-settings"></i> Account Setting</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#"><i class="fa fa-power-off"></i> Logout</a></li>
                    </ul>
                </div>
            </li>
            -->


        </ul>
    </div>
</nav>
</header>

app/views/shared/_leftside.html.erb
<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->

<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- User profile -->
        <div class="user-profile">
            <!-- User profile image -->
            <div class="profile-img"> <img src="/assets/users/profile.png" alt="user" /> 
                     <!-- this is blinking heartbit-->
                    <div class="notify setpos"> <span class="heartbit"></span> <span class="point"></span> </div>
            </div>
            <!-- User profile text-->
            <div class="profile-text"> 
                    <h5>Admin</h5>
                    <a href="#" class="dropdown-toggle u-dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"><i class="mdi mdi-settings"></i></a>
                     <a href="#" class="" data-toggle="tooltip" title="Email"><i class="mdi mdi-gmail"></i></a>
                    <a href="pages-login.html" class="" data-toggle="tooltip" title="Logout"><i class="mdi mdi-power"></i></a>

                <div class="dropdown-menu animated flipInY">
              
                </div>
            </div>
        </div>
        <!-- End User profile text-->




        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                 <li class="nav-devider"></li>
                <li class="nav-small-cap">SCHOOL MANAGEMENT</li>
                <li> <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-gauge"></i><span class="hide-menu">Dashboard </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="index.html">Minimal </a></li>
                        <li><a href="index2.html">Analytical</a></li>
                        <li><a href="index3.html">Demographical</a></li>
                        <li><a href="index4.html">Modern</a></li>
                    </ul>
                </li>
                <li <%=@caption_button_student=='ViewStudent'? 'class=active' : ''%> <%=@caption_button_student=='ViewPerformance'? 'class=active' : ''%> <%=@caption_button_student=='Update'? 'class=active' : ''%> <%=@caption_button_student_performance=='Update'? 'class=active' : ''%> > <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-account-multiple"></i><span class="hide-menu">Students</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li>    
                            <% if @caption_button_student=='ViewStudent' %>                     
                                <%= link_to 'View Student', students_path, class:'active' %>
                            <% else %>
                                <%= link_to 'View Student', students_path %>
                            <% end %>
                        </li>

                        <li>
                        
                            <% if @caption_button_student=='Update' %>
                                 <%= link_to 'Update Student', new_student_path, class:'active' %>  
                            <%else%>
                                 <%= link_to 'Register Student', new_student_path %>     
                            <%end%>
                           
                        </li>



                        <li>
                            <% if @caption_button_student=='ViewPerformance' %>  
                                 <%= link_to 'View Performance', student_performances_path, class:'active' %>
                            <% else %>
                                <%= link_to 'View Performance', student_performances_path %>   
                            <%end%>
                        </li>
                        <li>
                            <% if @caption_button_student_performance=='Update' %>
                                <%= link_to 'Update Performance', new_student_performance_path, class:'active' %>  
                            <%else%>
                                <%= link_to 'Add Performance', new_student_performance_path %>     
                            <%end%>
                               
                        
                        </li>

                    </ul>
                </li>
                <li <%=@caption_button_school=='Update'? 'class=active' : ''%><%=@caption_button_student_school=='Update'? 'class=active' : ''%> > <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-city"></i><span class="hide-menu">Schools</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li>
                            <%= link_to 'View School', schools_path %>
                        </li>

                        <li>                        
                            <% if @caption_button_school=='Update' %>
                                    <%= link_to 'Update School', new_school_path, class:'active' %>  
                            <%else%>
                                    <%= link_to 'Add School', new_school_path %>     
                            <%end%>
                        
                        </li>
                        
                        <li>                       
                         
                                <%= link_to 'View Student', student_schools_path %>
   
                        </li>
                        <li>
                        
                        <% if @caption_button_student_school=='Update' %>
                                <%= link_to 'Update Student', new_student_school_path, class:'active' %>  
                        <%else%>   
                                <%= link_to 'Add Student', new_student_school_path %>  
                        <%end%>
                             
                        
                        </li>

                    </ul>
                </li>
                <li <%=@caption_button_report=='ReportPerformancePDF'? 'class=active' : ''%><%=@caption_button_report=='ReportPerformanceGraph'? 'class=active' : ''%>> <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-book-open"></i><span class="hide-menu">Reports</span></a>
                    <ul aria-expanded="false" class="collapse">

                        <li>
                          
                            <% if @caption_button_report=='ReportPerformancePDF' %>  
                                <%= link_to 'Study Performance(PDF)', reports_performance_pdf_path, class:'active' %>
                            <% else %>
                                <%= link_to 'Study Performance(PDF)', reports_performance_pdf_path %>   
                            <%end%>

                        </li>
                        <li>
                            <% if @caption_button_report=='ReportPerformanceGraph' %>  
                                <%= link_to 'Performance(Graph)', reports_performance_graph_path, class:'active' %>
                            <% else %>
                                <%= link_to 'Performance (Graph)', reports_performance_graph_path %>   
                            <%end%>

                        </li>

                    </ul>
                </li>


                <li class="nav-small-cap">USER MANAGEMENT</li>
                <li  <%=@caption_button_user=='Update'? 'class=active' : ''%>> <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-file"></i><span class="hide-menu">User Permission</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li>
                        <%= link_to 'View User', users_path %>
                        <li>
                        <% if @caption_button_user=='Update' %>
                            <%= link_to 'Update User', new_user_path, class:'active' %>  
                        <%else%>   
                                <%= link_to 'Create User', new_user_path %>  
                        <%end%>
                        </li>
                        <li><a style="color:grey">Create Groups</a></li>                        
                        <li><a style="color:grey">Permission</a></li>
                                       
                    </ul>
                </li>


               
             
                 
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>


<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->