config/routes.rb
Rails.application.routes.draw do

  namespace 'api' do
      namespace 'v1' do
        resources :students, only: :index
        get 'students/get_student'
      end
  end

  resources :student_performances
  resources :student_schools
  resources :schools
  resources :students
  resources :users
  
  #resources :reports, only: [:show]
  get 'reports/index'
  get 'reports/performance_pdf' , to: 'reports#performance_pdf'
  get 'reports/pdf' , to: 'reports#show'
  get 'reports/performance_graph' , to: 'reports#performance_graph'
  

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

 
  root 'sessions#new'



  


  get '/search' => 'welcome#index', :as => 'search_page'
  get 'students/register' => 'students#new', :as => 'register'
  get '/students/student_register', to: 'students#new'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/school.rb
class School < ApplicationRecord
    has_many :student_schools
    has_many :students, through: :student_schools

    #the association between school and student_performance
    has_many :student_performances
    #the association between school and student through student_performance
    has_many :students, through: :student_performances
   
    validates :school_code, presence: true, length: {minimum: 3, maximum: 5}
    validates_uniqueness_of :school_code
    validates :school_name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :school_name

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
     # the first code in action show, edit, update and destroy are the same, we hate the duplicated code, use before_filter to avoid.
    # duplicate code is @school=school.find(params[:id])
    # Refactor
    before_action :find_school, only: [:show, :edit, :update, :destroy]
    
        # this action method for diplay list of School
        # # GET /schools
        def index
            @school=School.all
        end
        
        #this action method for getting information detail for a School
        # GET /schools/1
        def show
             # Look up the existing model record based
             # on an ID from the request path.
             #@school=School.find(params[:id])
        end
        #this action method for new School when user click button new School
        # # GET /schools/new
        def new
            @school=School.new
            @caption_button_school="Add"
        end
    
        #this action method for save School information into database when user click on button register
        # POST /schools
        def create 
            @school = School.new(school_params)
            if @school.save
              redirect_to edit_school_path(@school)
            else
              render :new
            end   
        end    
        #this action method for getting a School's information to edit when user click on button edit
        #GET /schools/1/edit
        def edit
            #@school = School.find(params[:id])
            @caption_button_school="Update" #this variable use to cheng the lable of button in School form partial to Update
    
        end
    
        #this action method for update a School's information into database when user click button update
        ## PATCH/PUT /schools/1
        def update
            #@school = School.find(params[:id])
            # the existing model record. 
            if @school.update(school_params)
    
                # Redirect the browser to edit of School
                redirect_to edit_school_path
              else
                # Redirect the browser to edit of School
                render :edit
              end
          end
    
        #this action method for deleting a School's information from database when user click on button delete
        def destroy
            #@school= School.find(params[:id])
            @school.destroy
            redirect_to schools_path
          end
    
        #this method is used for getting information from parameter when user click on button register or update
        #is used to filter the trusted parameters with a white list
        # Never trust parameters from the scary internet, only allow the white list through
        private
        def school_params
          params.require(:school).permit(:school_code, :school_name)
        end
    
        # Use callbacks to share common setup or constraints between actions.
        def find_school
            # Look up the existing model record based
            # on an ID from the request path.
            @school = School.find(params[:id])
          end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%=form_for @school do |f| %>
    
    <div class="card">
    <div class="card-body">
        <h4 class="card-title" style="color:brown;">School information</h4>
        <hr class="m-t-0 m-b-40"> 
    
        <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label text-left col-md-4">School Code</label>
                        <div class="col-md-8">
                            
                            <%=f.text_field :school_code , {class: 'form-control',required: true}%>
    
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label text-left col-md-4">School Name</label>
                        <div class="col-md-8">
                        <%=f.text_field :school_name , {class: 'form-control'}%>
                        </div>
                    </div>
                </div>
        </div>
    

    
      
        <hr class="m-t-0 m-b-40">
    
        <div class="container text-center">              
                <div class="row button-group">    
                
                    <div class="col-lg-2 col-md-3 col-sm-4">
                       
                       <%= button_tag( :class => "btn btn-block btn-outline-success btn-rounded") do %>
                            <i class="fa fa-file-o"></i> <%=@caption_button_school%>
                        <% end %>
                    </div>

                    <% if @caption_button_school=='Update' %>
                        <div class="col-lg-2 col-md-3 col-sm-4">
                        
                            <%= button_tag(:type => 'button', :class => "btn btn-block btn-outline-success btn-rounded", :onclick => "javascript:location.href='#{new_school_path()}'"    ) do %>
                                <i class="fa fa-file-o"> &nbsp;</i> New School
                            <% end %>


                        </div>
                    <%end%>


                    <div class="col-lg-2 col-md-3 col-sm-4">   
                                          
                            <%= button_tag(:type => 'button', :class => "btn btn-block btn-outline-success btn-rounded", :onclick => "javascript:location.href='#{schools_path()}'"    ) do %>
                                <i class="fa fa-search-plus"></i> Go Find
                            <% end %>
                     </div>
        
    
                </div>
                
    
        </div>
    
        
     </div><!-- end card body-->
    </div> <!-- end card -->
    
    
    <%end%>

app/views/schools/edit.html.erb
<%= render 'form' %>

app/views/schools/index.html.erb
<div class="card">
<div class="card-body">
    <h4 class="card-title" style="color:brown;">School information</h4>
    <hr class="m-t-0 m-b-40"> 

    <div class="row">
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label text-left col-md-4">School Code</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" id="name_kh" name="name_kh">
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label text-left col-md-4">School Name</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" id="name_kh" name="name_kh">
                    </div>
                </div>
            </div>
    </div>





    <hr class="m-t-0 m-b-40">

    <div class="container text-center">              
            <div class="row button-group">              
                    <div class="col-lg-2 col-md-3 col-sm-4">    
                        
                        <%= button_tag(:type => 'button', :class => "btn btn-block btn-outline-success btn-rounded", :onclick => "javascript:location.href='#{students_path()}'"    ) do %>
                            <i class="fa fa-search-plus">&nbsp;</i>Find
                        <% end %>
                    </div>
    
                    <div class="col-lg-2 col-md-3 col-sm-4">
                           
                            <%= button_tag(:type => 'button', :class => "btn btn-block btn-outline-success btn-rounded", :onclick => "javascript:location.href='#{new_student_path()}'"    ) do %>
                                <i class="fa fa-file-o"> &nbsp;</i> New School
                            <% end %>


                    </div>
            </div>
            

    </div>

    
 </div><!-- end card body-->
</div> <!-- end card -->





<div class="card">
<div class="card-body"> 
  <div class="row">
          <div class="col-12">
              
                  <div class="table-responsive m-t-40">
                          <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                              <thead>
                                  <tr>
                                      <th>No. </th>
                                      <th>School Code</th>
                                      <th>School Name</th>
                                   
                                      <th>Action</th>
                                  </tr>
                              </thead>

                              <tbody>
                                <% i=0 %>
                                <%@school.each do |school| %>
                                    <%i=i+1%>
                                    <tr>
                                    <td><%=i%></td>
                                    <td><%=school.school_code%></td>
                                    <td><%=school.school_name%></td>

                                    <td>
                                    <!-- Example single danger button -->
                                    <div class="btn-group">
                                            <button type="button" class="btn btn-sm btn-rounded btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="ti-settings"></i>
                                            </button>
                                            <div class="dropdown-menu">
                                               
                                                <%= link_to 'Delete', school_path(school), class:'dropdown-item' %>
                                                <%= link_to 'Edit', edit_school_path(school), class:'dropdown-item' %>
                                                
                                              
                                            </div>
                                        </div>

                                    </td>
                                </tr>   

                                <%end%>    

                               </tbody>
                          </table>
                      </div>
          </div>
  </div>
</div>
</div>

app/views/schools/new.html.erb
<%= render 'form' %>