config/routes.rb
Rails.application.routes.draw do

  namespace 'api' do
      namespace 'v1' do
        resources :students, only: :index
        get 'students/get_student'
      end
  end

  resources :student_performances
  resources :student_schools
  resources :schools
  resources :students
  resources :users
  
  #resources :reports, only: [:show]
  get 'reports/index'
  get 'reports/performance_pdf' , to: 'reports#performance_pdf'
  get 'reports/pdf' , to: 'reports#show'
  get 'reports/performance_graph' , to: 'reports#performance_graph'
  

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

 
  root 'sessions#new'



  


  get '/search' => 'welcome#index', :as => 'search_page'
  get 'students/register' => 'students#new', :as => 'register'
  get '/students/student_register', to: 'students#new'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    
    def index
       
    end

    def performance_pdf

        @student_filter=StudentPerformance.new #this variable for using with form_for for searching       
        performance_query
    end

    def show
        @student_performance=performance_query
        respond_to do |format|
            format.html
            format.pdf do
                pdf=Prawn::Document.new
                #pdf.text "Hello world"
                pdf=PerformancePdf.new(@student_performance)
                send_data pdf.render, 
                filename:"performance_.pdf",
                type: 'application/pdf',
                disposition: 'inline'

                #filename: "export.pdf",
                #type: 'application/pdf',
                #disposition: 'inline'
            end
        end

        

    end


    def performance_query

              
                #for fix error first time loading
                 if params[:student_performance].present?
                     @school_year = params[:student_performance][:school_year]
                     @school_id = params[:student_performance][:school_id]
                     @grade = params[:student_performance][:grade]
                     @student_name =params[:student_performance][:student_name]
                     @caption_button_report="ReportPerformancePDF" # for hight on menu when click on search
                     @student_performance=StudentPerformance.joins(:student).order(:id)
                 else
                     @student_performance=StudentPerformance.order(:id) # first time load
                 end
                
                 @student_performance=@student_performance.where(school_year: @school_year) if @school_year.present?
                 @student_performance=@student_performance.where(school_id: @school_id) if @school_id.present?
                 @student_performance=@student_performance.where(grade: @grade) if @grade.present?
                 @student_performance=@student_performance.where("student_name like ?", "%#{@student_name}%") if @student_name.present?
      
                 @student_performance
    end





    def performance_graph

        @student_filter=StudentPerformance.new #this variable for using with form_for for searching       
        
                #for fix error first time loading
                 if params[:student_performance].present?
                     @school_year = params[:student_performance][:school_year]
                     @school_id = params[:student_performance][:school_id]
                     @grade = params[:student_performance][:grade]
                     @student_name =params[:student_performance][:student_name]
                     @caption_button_report="ReportPerformanceGraph" # for hight on menu when click on search
                     @student_performance=StudentPerformance.joins(:student).order(:id)
                 else
                     @student_performance=StudentPerformance.order(:id) # first time load
                 end
                
                 @student_performance=@student_performance.where(school_year: @school_year) if @school_year.present?
                 @student_performance=@student_performance.where(school_id: @school_id) if @school_id.present?
                 @student_performance=@student_performance.where(grade: @grade) if @grade.present?
                 @student_performance=@student_performance.where("student_name like ?", "%#{@student_name}%") if @student_name.present?
        
        
    end



    

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.erb
<h1>Index</h1>

app/views/reports/performance_pdf.html.erb
<%
#[['Text', Value], ['Text', Value]]
school_year=[]                        
(2017..2019).each do |i|
    school_year.push([i.to_s+'-'+(i+1).to_s,i.to_s+'-'+(i+1).to_s])
end

grade=[]
(1..12).each do |i|
    grade.push(i.to_s)
end

%>

<%= form_for(@student_filter, :url=> reports_performance_pdf_path, :html => { :method => 'GET' }) do |f| %> 
        
<div class="card">
    <div class="card-body">
        <h4 class="card-title" style="color:brown;">Student's Performance (PDF)</h4>
        <hr class="m-t-0 m-b-40"> 

        <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label text-left col-md-4">School Year</label>
                        <div class="col-md-8">
                        <%= f.select :school_year, options_for_select(school_year,:selected => @school_year), {include_blank: '-- Select One --'}, {class: 'form-control'}%>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label text-left col-md-4">School Name</label>
                        <div class="col-md-8">
                        <%= f.collection_select :school_id, School.order(:school_name),:id ,:school_name, { include_blank: '-- Select One --' }, { class: "form-control" } %>
                        </div>
                    </div>
                </div>
        </div>

        <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label text-left col-md-4">Grade</label>
                        <div class="col-md-8">
                        <%= f.select :grade, options_for_select(grade,:selected =>@grade), {include_blank: '-- Select One --'}, {class: 'form-control'}%>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label text-left col-md-4">Student Name</label>
                        <div class="col-md-8">
                        <%=f.text_field :student_name , {class: 'form-control',value:@student_name} %>
                        </div>
                    </div>
                </div>
        </div>






        <hr class="m-t-0 m-b-40">

        <div class="container text-center">              
                <div class="row button-group">              
                        <div class="col-lg-2 col-md-3 col-sm-4">    
                            


                            <%= button_tag(:type => 'submit', :class => "btn btn-block btn-outline-success btn-rounded" ) do %>
                                <i class="fa fa-search-plus">&nbsp;</i>Find
                            <% end %>

                        </div>
        
                        <div class="col-lg-2 col-md-3 col-sm-4">
                            
                                <%= button_tag(:type => 'button', :class => "btn btn-block btn-outline-success btn-rounded", :onclick => "javascript:location.href='#{reports_pdf_path()}.pdf'"    ) do %>
                                    <i class="fa fa-file-o"> &nbsp;</i> PDF
                                <% end %>


                        </div>
                </div>
                

        </div>

        
    </div><!-- end card body-->
</div> <!-- end card -->

<% end %>



<div class="card">
<div class="card-body"> 
  <div class="row">
          <div class="col-12">
              
                  <div class="table-responsive m-t-40">
                          <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                              <thead>
                                  <tr>
                                      <th>No. </th>
                                      <th>School Year</th>
                                      <th>School Name</th>
                                      <th>Grade</th>
                                      <th>Student Name</th>
                                      <th>Score S1</th>
                                      <th>Avg. S1</th>
                                      <th>Score S2</th>   
                                      <th>Avg. S2</th>                                   
                                      <th>Total Score</th>
                                      <th>Total Avg.</tha>
                                      <th>Result</th>
                                  </tr>
                              </thead>

                              <tbody>
                              
                                <% i=0 %>
                                <%@student_performance.each do |student_performance| %>
                                    <%i=i+1%>
                                    <%
                                    total_scoreS1=student_performance.math_s1+student_performance.khmer_s1+student_performance.social_s1
                                    avg_scoreS1=total_scoreS1/3

                                    total_scoreS2=student_performance.math_s2+student_performance.khmer_s2+student_performance.social_s2
                                    avg_scoreS2=total_scoreS2/3

                                    total_score=total_scoreS1+total_scoreS2
                                    avg_semester=total_score/2
                                    result=((avg_semester/total_score)*100)>60 ? "Pass" : "Fail"


                                    %>
                                    <tr>
                                    <td><%=i%></td>
                                    <td><%=student_performance.school_year%></td>
                                    <td><%=student_performance.school.school_name%></td>
                                    <td align="center"><%=student_performance.grade%></td> 
                                    <td><%=student_performance.student.student_name%></td>
                                    <td><%=total_scoreS1%></td>
                                    <td><%=avg_scoreS1%></td>
                                    <td><%=total_scoreS2%></td>
                                    <td><%=avg_scoreS2%></td>
                                    <td><%=total_score%></td>
                                    <td><%=avg_semester%></td>
                                    <td><%=result%></td>

                                </tr>   

                                <%end%>   

                               </tbody>
                          </table>
                      </div>
          </div>
  </div>
</div>
</div>

app/views/reports/show.html.erb
<% @student_performance.each do |item| %>
    H
<%end%>